require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRailsVersion: 5.0
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/bundle/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 24.1 # TODO: Lower to 15
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 8 # TODO: Lower to 6
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 19
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 13

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Minitest/MultipleAssertions:
  Enabled: false

Rails/HttpPositionalArguments:
  Exclude:
    - 'test/**/*'

Rails/I18nLocaleAssignment:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false # Escaping chars helps with syntax highlighting
