os: linux
dist: focal
language: ruby
cache: bundler
rvm:
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - ruby-head
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_edge.gemfile
jobs:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.4.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.1.gemfile
    - rvm: 2.5.9
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.6.7
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.7.3
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7.3
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7.3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 3.0.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 3.0.1
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 3.0.1
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5.2.gemfile
  fast_finish: true
